title: UCSC Slug Dining Chat Bot
description: A bot to see the food items currently being served at the UCSC dining halls from your favorite communication platforms!
remote_theme: "mmistakes/minimal-mistakes@4.14.2"
