title: UCSC Slug Dining Chat Bot
description: A bot to see the food items currently being served at the UCSC dining halls from your favorite communication platforms!
show_downloads: false
theme: jekyll-theme-cayman
